### ISSUE TITLE
[Job] --attach hangs when job ends too quickly

### ISSUE THREAD

**Issue by foxish** [signadot/cli#136]
I have a job that's just:

```
spec:
  namePrefix: my-job
  runnerGroup: hackspace-test-jobs
  script: |
    #!/bin/bash

    echo abc
```

This just hangs on the CLI even though the job has already completed. 
It works as expected when I specify `sleep 10`.

cc @daniel-de-vera @davixcky
